#!/usr/bin/env bash

function blue
{
  tput setaf 7; tput setab 4
  echo "$1"
  tput op
}

function red
{
  tput setaf 7; tput setab 1
  echo "$1"
  tput op
}



IOS_PROJECT="../openkit-ios/OpenKit.xcodeproj"
ANDROID_SDK_BUILD_FILE="../openkit-android/OpenKitSDK/build.xml"
ANDROID_UNITY_BUILD_FILE="../openkit-android/OpenKitUnity/build.xml" 
ANDROID_SDK_FOLDER="../openkit-android/OpenKitSDK"


UNITY_PLUGINS_FOLDER="OpenKitUnityPlugin/Assets/Plugins"
UNITY_PLUGINS_ANDROID_FOLDER="OpenKitUnityPlugin/Assets/Plugins/Android"
UNITY_PLUGINS_IOS_FOLDER="OpenKitUnityPlugin/Assets/Plugins/iOS"


echo "Do you want to build a debug or release package? Default is release. (d/r)"
read -e MORE
if [ $MORE == "d" ]
then
	CONFIG="Debug"
	ANT_TARGET="jar"
	LIB_OPENKIT_UNITY_BUILD_PATH="../openkit-ios/build/Debug-iphoneos/libOpenKitUnity.a"
	LIB_OPENKIT_BUILD_PATH="../openkit-ios/build/Debug-iphoneos/libOpenKit.a"
	INCLUDES_FOLDER="../openkit-ios/build/Debug-iphoneos/include/"
	RESOURCES_FOLDER="../openkit-ios/build/Debug-iphoneos/Resources/"
else
	CONFIG="Release"
	LIB_OPENKIT_UNITY_BUILD_PATH="../openkit-ios/build/Release-iphoneos/libOpenKitUnity.a"
	LIB_OPENKIT_BUILD_PATH="../openkit-ios/build/Release-universal/libOpenKit.a"
	INCLUDES_FOLDER="../openkit-ios/build/Release-universal/include/"
	RESOURCES_FOLDER="../openkit-ios/build/Release-universal/Resources/"
	ANT_TARGET="dist-jar"
fi

ERROR=0

function check_error
{
	if [ $? != 0 ]
	then
		red "There was an error with the previous command"
		ERROR=1
	fi
}


blue "Building $CONFIG"

blue "cleaning OpenKitSDK"
ant clean -f $ANDROID_SDK_BUILD_FILE
check_error

blue "cleaning OpenKitUnity - Android"
ant clean -f $ANDROID_UNITY_BUILD_FILE
check_error

#no longer building a jar out of OpenKitSDK, just need to build the SDK project and copy it over
blue "Building OpenKitSDK  $CONFIG"
ant $CONFIG -f $ANDROID_SDK_BUILD_FILE
check_error

blue "Building openkit-unity-plugin jar $CONFIG"
ant $ANT_TARGET -f $ANDROID_UNITY_BUILD_FILE
check_error

# Don't need to copy lib files anymore, since they are contained in the OpenKitSDK folder itself
#blue "Copying Android Libs files"
#cp -v ../openkit-android/OpenKitSDK/libs/* $UNITY_PLUGINS_ANDROID_FOLDER
#check_error

blue "Deleting OpenKitSDK folder and copying over OpenKitSDK folder"
rm -rf $UNITY_PLUGINS_ANDROID_FOLDER/OpenKitSDK
check_error
cp -r -v $ANDROID_SDK_FOLDER $UNITY_PLUGINS_ANDROID_FOLDER
check_error

blue "Copying OpenKitUnity JAR"
cp -v ../openkit-android/OpenKitUnity/bin/jars/openkit-unity-plugin.jar $UNITY_PLUGINS_ANDROID_FOLDER/OpenKitSDK/libs
check_error

blue "Deleting and Copying Facebook Android SDK"
rm -rf $UNITY_PLUGINS_ANDROID_FOLDER/facebook
check_error
cp -r -v ../openkit-android/Vendor/facebook $UNITY_PLUGINS_ANDROID_FOLDER
check_error
 
blue "Finished building and copying for Android $CONFIG"

blue "Building iOS $CONFIG"

blue "Cleaning OpenKit Project, all targets"
xcodebuild -alltargets clean -project $IOS_PROJECT
check_error

blue "Building OpenKit project, $CONFIG"
xcodebuild -project $IOS_PROJECT -configuration $CONFIG -target OpenKit
check_error

blue "Building OpenKitUnity Plugin, $CONFIG"
xcodebuild -project $IOS_PROJECT -configuration $CONFIG -target OpenKitUnity
check_error

blue "Copying libOpenKitUnity.a file"
cp -v $LIB_OPENKIT_UNITY_BUILD_PATH $UNITY_PLUGINS_IOS_FOLDER
check_error

blue "Copying libOpenKit.a to Unity project"
cp -v $LIB_OPENKIT_BUILD_PATH $UNITY_PLUGINS_IOS_FOLDER 
check_error

blue "Deleting include and resources folders"
rm -rf OpenKitUnityPlugin/Assets/Plugins/iOS/OpenKitResources/Resources
check_error
rm -rf OpenKitUnityPlugin/Assets/Plugins/iOS/OpenKitResources/include
check_error

blue "Copying include folder"
cp -r -v $INCLUDES_FOLDER OpenKitUnityPlugin/Assets/Plugins/iOS/OpenKitResources/include
check_error

blue "Copying Resources folder"
cp -r -v $RESOURCES_FOLDER OpenKitUnityPlugin/Assets/Plugins/iOS/OpenKitResources/Resources
check_error

blue "Finished building $CONFIG"

#Check for any errors
if [ $ERROR != 0 ]
then
	red "There was an error!"
fi